[[redirects]]
    from = "/api/*"
    to = "http://apis.data.go.kr/6430000/cbRecreationalForestInfoService/getRecreationalForestInfo:splat"
    status = 200

[[redirects]]
    from = "/"
    to = "index.html"
    status = 200
