[[redirects]]
    from = "/api/*"
    to = "https://api.odcloud.kr/api/15099285/v1/uddi:57e7fc08-b32c-482d-8dc7-ab02864a70b7:splat"
    status = 200

[[redirects]]
    from = "/"
    to = "index.html"
    status = 200
